baseurl: /lc-spring
encoding: utf-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

safe: false
hightlighter: true
excerpt_separator: "\n\n\n"
paginate: 5
